### ISSUE TITLE
[BUG] [CRASH] : AutomaticWildShape will not run, gives following error references:

### ISSUE THREAD

**Issue by AFodes** [LaytonGB/AutomaticWildShape#1]
Hey Layton, I absolutely love this API idea! I would SO MUCH rather use this than your 1st Wild Shape API, Druid Shift, or even macros with Token Mod. I am very, very new to coding, macros, and APIs, though, and I have no idea what these error messages me. Can you help me diagnose the problem? I would love to spread the word about your awesome API idea if I can get it running!

When I enable your script in the APIs for my game, I get the following error message:

**Error Code / Crash Message**
Your scripts are currently disabled due to an error that was detected. Please make appropriate changes to your script's code and click the "Save Script" button. We will then attempt to start running the scripts again. More info... If this script was installed from the Script Library, you might find help in the Community API Forum.

For reference, the error message generated was: ReferenceError: AST_name is not defined
ReferenceError: AST_name is not defined
    at apiscript.js:22411:26
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:154:1), <anonymous>:65:16)
    at Object.publish (eval at <anonymous> (/home/node/d20-api-server/api.js:154:1), <anonymous>:70:8)
    at checkForReady (/home/node/d20-api-server/api.js:1467:12)
    at /home/node/d20-api-server/api.js:1547:9
    at c (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:14:64)
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:560
    at hc (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:39:147)
    at Kd (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:546)
    at Id.Mb (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:489)

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by LaytonGB** [comment]
Hi @AFodes , unfortunately the error codes provided by Roll20 are often trash, and in this case there's not one bit of that error message that actually comes from my code, though my code is _probably_ the issue.

Because I'm working, in college, and facing final exams at the moment, I'm not going to be able to work on or test this issue for about a month or two. Assuming I've some free time after that I'll take a look.

**Comment by AFodes** [comment]
No worries, @LaytonGB! I'm a grad student and research assistant myself, so I'm also in the thick of things right now. My druid hardly uses her wildshape right now anyway, though whenever you do have the time to sort out this incredible script, I bet she would use it far more often!

By the way, I did make a new game to test AutomaticWildShape on its own and got the same message.

**Comment by LaytonGB** [comment]
> By the way, I did make a new game to test AutomaticWildShape on its own and got the same message.

That's very helpful! I'll give it some testing and get it working as soon as I can :)

**Comment by AFodes** [comment]
No worries! I also tested it with and without BetteR20 and VTTES, same kind of error message and non-response to !aws commands.

**Comment by LaytonGB** [comment]
The issue is fixed! Turns out I'd been using a variable that referenced something that didn't exist. I've no idea when that issue was put in, but it was blaring and obvious.

NOTE: The code now runs, but I can't vouch for the usability - it may work great! It may be littered with bugs. This was the second piece of coding I'd ever invested any time in and looking back on it, it's a mess. I remember using it though, so good luck and I hope things work great!

If you have any more issues please submit additional bug reports and I will get to them when I can.

**Comment by AFodes** [comment]
Great, thanks, Layton!
